security:
    password_hashers:
        App\Entity\SynstituteInstance:
            algorithm: auto

    providers:
        app_instance_provider:
            entity:
                class: App\Entity\SynstituteInstance
                property: identifier

    firewalls:
        dev:
            pattern: ^/(?:_(profiler|wdt)|css|images|js)/
            security: false

        main:
            stateless: true
            provider: app_instance_provider
            custom_authenticators:
                - App\Security\ApiKeyAuthenticator

    access_control:
        - { path: ^/health$, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_INSTANCE }
