parameters:
    admin_username_default: 'admin'
    admin_password_hash_default: ''

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Security\ApiKeyAuthenticator:
        arguments:
            $appEnv: '%kernel.environment%'
